spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetlink
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1007
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 테이블이 없으면 생성하고, 있으면 유지합니다.
    show-sql: true
